repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.13.0
    hooks:
      - id: commitizen
        stages:
          - commit-msg
  - hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - exclude: mkdocs.yml
        id: check-yaml
      - id: check-json
      - id: detect-private-key
      - id: check-merge-conflict
      - id: check-docstring-first
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.1.6
    hooks:
      - id: ruff-format
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
